openapi: 3.1.0
info:
  title: Platform Content Management Schemas
  version: 1.0.0

components:
  schemas:
    # ================== PLATFORM PAGE SCHEMAS ==================
    
    PlatformPage:
      type: object
      description: "Platform-level page content managed by Platform Administrators"
      properties:
        id:
          type: integer
          format: int64
          description: "Unique page ID"
          example: 1
        uuid:
          type: string
          format: uuid
          description: "Unique page UUID"
          example: "550e8400-e29b-41d4-a716-446655440001"
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: "Page title"
          example: "Platform Homepage"
        slug:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 1
          maxLength: 255
          description: "URL-friendly page identifier"
          example: "home"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: "Page description for SEO and internal reference"
          example: "Main platform homepage content"
        content:
          type: object
          description: "Structured JSON content for the page"
          additionalProperties: true
          example:
            hero:
              title: "Welcome to Stencil Platform"
              subtitle: "Enterprise Multi-Tenant CMS Solution"
              buttons:
                - text: "Get Started"
                  url: "/register"
                  type: "primary"
            features:
              - title: "Multi-Tenant Architecture"
                description: "Complete tenant isolation with schema-per-tenant"
                icon: "building"
        template:
          type: string
          default: "default"
          description: "Template identifier for rendering"
          example: "platform-homepage"
        meta_data:
          type: object
          nullable: true
          description: "SEO and custom metadata"
          additionalProperties: true
          example:
            seo:
              title: "Stencil Platform - Enterprise CMS"
              description: "Multi-tenant content management system for enterprises"
              keywords: ["CMS", "Multi-tenant", "Enterprise"]
        status:
          type: string
          enum: ["draft", "published", "archived"]
          default: "draft"
          description: "Page publication status"
          example: "published"
        is_homepage:
          type: boolean
          default: false
          description: "Whether this page is the platform homepage"
          example: true
        sort_order:
          type: integer
          default: 0
          description: "Sort order for page listing"
          example: 1
        language:
          type: string
          minLength: 2
          maxLength: 5
          default: "en"
          description: "Page language code (ISO 639-1)"
          example: "en"
        parent_id:
          type: integer
          format: int64
          nullable: true
          description: "Parent page ID for hierarchical structure"
          example: null
        published_at:
          type: string
          format: date-time
          nullable: true
          description: "Publication timestamp"
          example: "2025-12-03T15:30:00Z"
        created_by:
          type: integer
          format: int64
          description: "Platform admin user ID who created the page"
          example: 1
        created_at:
          type: string
          format: date-time
          description: "Creation timestamp"
          example: "2025-12-03T14:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: "Last update timestamp"
          example: "2025-12-03T15:30:00Z"
        versions:
          type: array
          items:
            $ref: '#/components/schemas/PlatformPageVersion'
          description: "Page versions history"
        current_version:
          $ref: '#/components/schemas/PlatformPageVersion'
          description: "Current active version"
        children:
          type: array
          items:
            $ref: '#/components/schemas/PlatformPage'
          description: "Child pages"
      required:
        - id
        - uuid
        - title
        - slug
        - content
        - status
        - created_by
        - created_at
        - updated_at

    PlatformPageVersion:
      type: object
      description: "Version history for platform pages"
      properties:
        id:
          type: integer
          format: int64
          description: "Version ID"
          example: 1
        page_id:
          type: integer
          format: int64
          description: "Associated page ID"
          example: 1
        version_number:
          type: integer
          minimum: 1
          description: "Sequential version number"
          example: 2
        content:
          type: object
          description: "Page content at this version"
          additionalProperties: true
        meta_data:
          type: object
          nullable: true
          description: "Metadata at this version"
          additionalProperties: true
        change_description:
          type: string
          nullable: true
          maxLength: 500
          description: "Description of changes made in this version"
          example: "Updated homepage hero section and added new feature highlights"
        created_by:
          type: integer
          format: int64
          description: "Platform admin who created this version"
          example: 1
        is_current:
          type: boolean
          default: false
          description: "Whether this is the current active version"
          example: true
        created_at:
          type: string
          format: date-time
          description: "Version creation timestamp"
          example: "2025-12-03T15:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: "Version update timestamp"
          example: "2025-12-03T15:30:00Z"
      required:
        - id
        - page_id
        - version_number
        - content
        - created_by
        - is_current
        - created_at
        - updated_at

    PlatformContentBlock:
      type: object
      description: "Reusable content blocks for platform and tenant templates"
      properties:
        id:
          type: integer
          format: int64
          description: "Content block ID"
          example: 1
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: "Human-readable block name"
          example: "Hero Section"
        identifier:
          type: string
          pattern: '^[a-z0-9-_]+$'
          minLength: 1
          maxLength: 255
          description: "Unique block identifier"
          example: "hero-section-v1"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: "Block description and usage notes"
          example: "Standard hero section with title, subtitle, and CTA buttons"
        schema:
          type: object
          description: "JSON schema defining the block structure"
          additionalProperties: true
          example:
            type: "object"
            properties:
              title:
                type: "string"
                maxLength: 100
              subtitle:
                type: "string"
                maxLength: 200
              buttons:
                type: "array"
                items:
                  type: "object"
                  properties:
                    text:
                      type: "string"
                    url:
                      type: "string"
                    type:
                      type: "string"
                      enum: ["primary", "secondary"]
        default_content:
          type: object
          nullable: true
          description: "Default content structure for new instances"
          additionalProperties: true
          example:
            title: "Welcome to Our Platform"
            subtitle: "Transform your business with our solutions"
            buttons:
              - text: "Get Started"
                url: "/register"
                type: "primary"
        category:
          type: string
          default: "general"
          description: "Block category for organization"
          example: "hero"
        is_reusable:
          type: boolean
          default: true
          description: "Whether this block can be reused across pages"
          example: true
        is_active:
          type: boolean
          default: true
          description: "Whether this block is active and available"
          example: true
        is_template:
          type: boolean
          default: false
          description: "Whether this block is available as a tenant template"
          example: true
        created_at:
          type: string
          format: date-time
          description: "Creation timestamp"
          example: "2025-12-03T14:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: "Last update timestamp"
          example: "2025-12-03T15:30:00Z"
      required:
        - id
        - name
        - identifier
        - schema
        - category
        - is_reusable
        - is_active
        - is_template
        - created_at
        - updated_at

    # ================== REQUEST SCHEMAS ==================
    
    CreatePlatformPageRequest:
      type: object
      description: "Request to create a new platform page"
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: "Page title"
          example: "About Our Platform"
        slug:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 1
          maxLength: 255
          description: "URL-friendly identifier (auto-generated if not provided)"
          example: "about"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: "Page description"
          example: "Information about our platform and mission"
        content:
          type: object
          description: "Structured page content"
          additionalProperties: true
          example:
            sections:
              - type: "hero"
                title: "About Our Platform"
                content: "Learn more about our mission and values"
        template:
          type: string
          default: "default"
          description: "Template identifier"
          example: "about-page"
        meta_data:
          type: object
          nullable: true
          description: "SEO and custom metadata"
          additionalProperties: true
        status:
          type: string
          enum: ["draft", "published", "archived"]
          default: "draft"
          description: "Initial publication status"
          example: "draft"
        language:
          type: string
          minLength: 2
          maxLength: 5
          default: "en"
          description: "Page language"
          example: "en"
        parent_id:
          type: integer
          format: int64
          nullable: true
          description: "Parent page ID"
          example: null
        is_homepage:
          type: boolean
          default: false
          description: "Set as platform homepage"
          example: false
        sort_order:
          type: integer
          default: 0
          description: "Sort order"
          example: 10
      required:
        - title
        - content

    UpdatePlatformPageRequest:
      type: object
      description: "Request to update a platform page"
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: "Updated page title"
          example: "About Our Platform - Updated"
        slug:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 1
          maxLength: 255
          description: "Updated URL slug"
          example: "about-updated"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: "Updated description"
        content:
          type: object
          description: "Updated page content"
          additionalProperties: true
        template:
          type: string
          description: "Updated template"
          example: "about-page-v2"
        meta_data:
          type: object
          nullable: true
          description: "Updated metadata"
          additionalProperties: true
        status:
          type: string
          enum: ["draft", "published", "archived"]
          description: "Updated status"
          example: "published"
        is_homepage:
          type: boolean
          description: "Homepage setting"
          example: false
        sort_order:
          type: integer
          description: "Updated sort order"
          example: 5
        language:
          type: string
          minLength: 2
          maxLength: 5
          description: "Updated language"
          example: "en"
        parent_id:
          type: integer
          format: int64
          nullable: true
          description: "Updated parent page"
        create_version:
          type: boolean
          default: true
          description: "Create new version on update"
          example: true
        change_description:
          type: string
          nullable: true
          maxLength: 500
          description: "Description of changes made"
          example: "Updated content and added new sections"

    CreatePlatformContentBlockRequest:
      type: object
      description: "Request to create a new platform content block"
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: "Block name"
          example: "Feature Showcase"
        identifier:
          type: string
          pattern: '^[a-z0-9-_]+$'
          minLength: 1
          maxLength: 255
          description: "Unique identifier"
          example: "feature-showcase-v1"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: "Block description"
          example: "Showcase platform features with icons and descriptions"
        schema:
          type: object
          description: "JSON schema for block structure"
          additionalProperties: true
          example:
            type: "object"
            properties:
              features:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                    description:
                      type: "string"
                    icon:
                      type: "string"
        default_content:
          type: object
          nullable: true
          description: "Default content"
          additionalProperties: true
        category:
          type: string
          default: "general"
          description: "Block category"
          example: "features"
        is_reusable:
          type: boolean
          default: true
          description: "Reusable flag"
          example: true
        is_template:
          type: boolean
          default: false
          description: "Available as tenant template"
          example: true
      required:
        - name
        - identifier
        - schema

    # ================== RESPONSE COLLECTIONS ==================
    
    PlatformPagesResponse:
      type: object
      description: "Collection of platform pages"
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/PlatformPage'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
      required:
        - success
        - data

    PlatformPageResponse:
      type: object
      description: "Single platform page response"
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/PlatformPage'
        meta:
          $ref: '#/components/schemas/ResponseMeta'
      required:
        - success
        - data

    PlatformContentBlocksResponse:
      type: object
      description: "Collection of platform content blocks"
      properties:
        success:
          type: boolean
          example: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/PlatformContentBlock'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
      required:
        - success
        - data

    # ================== COMMON SCHEMAS ==================
    
    PaginationMeta:
      type: object
      description: "Pagination metadata"
      properties:
        current_page:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 5
        per_page:
          type: integer
          example: 20
        total:
          type: integer
          example: 95
        from:
          type: integer
          example: 1
        to:
          type: integer
          example: 20
        timestamp:
          type: string
          format: date-time
          example: "2025-12-03T15:30:00Z"
        request_id:
          type: string
          example: "req_platform_123456"
      required:
        - current_page
        - last_page
        - per_page
        - total
        - timestamp
        - request_id

    ResponseMeta:
      type: object
      description: "Response metadata"
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-12-03T15:30:00Z"
        request_id:
          type: string
          example: "req_platform_123456"
        platform_context:
          type: string
          example: "platform_admin"
      required:
        - timestamp
        - request_id
        - platform_context