openapi: 3.0.3
info:
  title: Financial Reports Module API
  version: 1.0.0

paths:
  /api/v1/admin/financial/dashboard:
    get:
      tags:
        - Financial Reports
      summary: Get financial dashboard (Admin)
      description: Retrieve financial overview and key metrics
      security:
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          schema:
            type: string
            enum: [today, week, month, year, custom]
            default: month
        - name: startDate
          in: query
          schema:
            type: string
            format: date
          description: Required if period is custom
        - name: endDate
          in: query
          schema:
            type: string
            format: date
          description: Required if period is custom
      responses:
        '200':
          description: Dashboard data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/FinancialDashboard'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/financial/revenue:
    get:
      tags:
        - Financial Reports
      summary: Get revenue report (Admin)
      description: Retrieve detailed revenue breakdown
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: groupBy
          in: query
          schema:
            type: string
            enum: [day, week, month]
            default: day
      responses:
        '200':
          description: Revenue report retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/RevenueReport'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/financial/expenses:
    get:
      tags:
        - Financial Reports
      summary: Get expenses report (Admin)
      description: Retrieve detailed expenses breakdown
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: category
          in: query
          schema:
            type: string
          description: Filter by expense category
      responses:
        '200':
          description: Expenses report retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/ExpensesReport'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Financial Reports
      summary: Add expense (Admin)
      description: Record new business expense
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseRequest'
      responses:
        '201':
          description: Expense recorded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Expense'
                  message:
                    type: string
                    example: Expense recorded successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/financial/expenses/{id}:
    put:
      tags:
        - Financial Reports
      summary: Update expense (Admin)
      description: Update existing expense record
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseRequest'
      responses:
        '200':
          description: Expense updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Expense'
                  message:
                    type: string
                    example: Expense updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    delete:
      tags:
        - Financial Reports
      summary: Delete expense (Admin)
      description: Delete expense record
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Expense deleted successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/SuccessResponse'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/financial/profit-loss:
    get:
      tags:
        - Financial Reports
      summary: Get profit & loss report (Admin)
      description: Retrieve profit and loss statement
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Profit & loss report retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/ProfitLossReport'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/financial/export:
    post:
      tags:
        - Financial Reports
      summary: Export financial report (Admin)
      description: Export report in PDF or Excel format
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reportType
                - format
                - startDate
                - endDate
              properties:
                reportType:
                  type: string
                  enum: [revenue, expenses, profit-loss, dashboard]
                format:
                  type: string
                  enum: [pdf, excel]
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
      responses:
        '200':
          description: Report exported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      downloadUrl:
                        type: string
                        format: uri
                      expiresAt:
                        type: string
                        format: date-time
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

components:
  schemas:
    FinancialDashboard:
      type: object
      properties:
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        revenue:
          type: object
          properties:
            total:
              type: number
              format: float
              example: 125000000
            growth:
              type: number
              format: float
              example: 15.5
              description: Percentage growth compared to previous period
        expenses:
          type: object
          properties:
            total:
              type: number
              format: float
              example: 75000000
            growth:
              type: number
              format: float
              example: 8.2
        profit:
          type: object
          properties:
            total:
              type: number
              format: float
              example: 50000000
            margin:
              type: number
              format: float
              example: 40
              description: Profit margin percentage
        orders:
          type: object
          properties:
            total:
              type: integer
              example: 342
            averageValue:
              type: number
              format: float
              example: 365497.08
        topProducts:
          type: array
          items:
            type: object
            properties:
              productId:
                $ref: '../components/schemas/common.yaml#/UUID'
              name:
                type: string
              revenue:
                type: number
                format: float
              unitsSold:
                type: integer

    RevenueReport:
      type: object
      properties:
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        summary:
          type: object
          properties:
            totalRevenue:
              type: number
              format: float
            totalOrders:
              type: integer
            averageOrderValue:
              type: number
              format: float
        breakdown:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              revenue:
                type: number
                format: float
              orders:
                type: integer
        byProduct:
          type: array
          items:
            type: object
            properties:
              productId:
                $ref: '../components/schemas/common.yaml#/UUID'
              name:
                type: string
              revenue:
                type: number
                format: float
              quantity:
                type: integer

    ExpensesReport:
      type: object
      properties:
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        summary:
          type: object
          properties:
            totalExpenses:
              type: number
              format: float
            expenseCount:
              type: integer
        byCategory:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
              total:
                type: number
                format: float
              percentage:
                type: number
                format: float
        expenses:
          type: array
          items:
            $ref: '#/components/schemas/Expense'

    Expense:
      type: object
      properties:
        id:
          $ref: '../components/schemas/common.yaml#/UUID'
        category:
          type: string
          example: Materials
        description:
          type: string
          example: Vinyl material purchase
        amount:
          type: number
          format: float
          example: 5000000
        date:
          type: string
          format: date
        vendor:
          type: string
          nullable: true
        receipt:
          type: string
          format: uri
          nullable: true
        recordedBy:
          type: object
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ExpenseRequest:
      type: object
      required:
        - category
        - description
        - amount
        - date
      properties:
        category:
          type: string
          minLength: 2
        description:
          type: string
          minLength: 5
        amount:
          type: number
          format: float
          minimum: 0
        date:
          type: string
          format: date
        vendor:
          type: string
          nullable: true
        receipt:
          type: string
          format: uri
          nullable: true

    ProfitLossReport:
      type: object
      properties:
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        revenue:
          type: object
          properties:
            sales:
              type: number
              format: float
            otherIncome:
              type: number
              format: float
            total:
              type: number
              format: float
        costOfGoodsSold:
          type: number
          format: float
        grossProfit:
          type: number
          format: float
        operatingExpenses:
          type: object
          properties:
            materials:
              type: number
              format: float
            labor:
              type: number
              format: float
            overhead:
              type: number
              format: float
            marketing:
              type: number
              format: float
            other:
              type: number
              format: float
            total:
              type: number
              format: float
        netProfit:
          type: number
          format: float
        profitMargin:
          type: number
          format: float
          description: Percentage
