openapi: 3.0.3
info:
  title: Inventory Management Module API
  version: 1.0.0

paths:
  /api/v1/admin/inventory:
    get:
      tags:
        - Inventory Management
      summary: Get inventory overview (Admin)
      description: Retrieve inventory status for all products
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../components/parameters/common.yaml#/PageQuery'
        - $ref: '../components/parameters/common.yaml#/PerPageQuery'
        - $ref: '../components/parameters/common.yaml#/SearchQuery'
        - $ref: '../components/parameters/common.yaml#/SortQuery'
        - name: lowStock
          in: query
          schema:
            type: boolean
          description: Filter products with low stock
        - name: outOfStock
          in: query
          schema:
            type: boolean
          description: Filter out of stock products
      responses:
        '200':
          description: Inventory retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/InventoryItem'
                  meta:
                    allOf:
                      - $ref: '../components/schemas/common.yaml#/PaginationMeta'
                      - type: object
                        properties:
                          summary:
                            $ref: '#/components/schemas/InventorySummary'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/inventory/{productId}:
    get:
      tags:
        - Inventory Management
      summary: Get product inventory (Admin)
      description: Retrieve detailed inventory for specific product
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product inventory retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/InventoryDetail'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    put:
      tags:
        - Inventory Management
      summary: Update product inventory (Admin)
      description: Update stock quantity and alerts
      security:
        - bearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryUpdateRequest'
      responses:
        '200':
          description: Inventory updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/InventoryDetail'
                  message:
                    type: string
                    example: Inventory updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/inventory/movements:
    get:
      tags:
        - Stock Movements
      summary: Get stock movements (Admin)
      description: Retrieve history of all stock movements
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../components/parameters/common.yaml#/PageQuery'
        - $ref: '../components/parameters/common.yaml#/PerPageQuery'
        - name: productId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by product ID
        - name: type
          in: query
          schema:
            type: string
            enum: [in, out, adjustment]
          description: Filter by movement type
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Stock movements retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/StockMovement'
                  meta:
                    $ref: '../components/schemas/common.yaml#/PaginationMeta'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Stock Movements
      summary: Create stock movement (Admin)
      description: Record new stock in/out or adjustment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockMovementRequest'
      responses:
        '201':
          description: Stock movement created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/StockMovement'
                  message:
                    type: string
                    example: Stock movement recorded successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/inventory/alerts:
    get:
      tags:
        - Inventory Management
      summary: Get stock alerts (Admin)
      description: Retrieve all low stock and out of stock alerts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Stock alerts retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      lowStock:
                        type: array
                        items:
                          $ref: '#/components/schemas/StockAlert'
                      outOfStock:
                        type: array
                        items:
                          $ref: '#/components/schemas/StockAlert'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

components:
  schemas:
    InventoryItem:
      type: object
      properties:
        productId:
          $ref: '../components/schemas/common.yaml#/UUID'
        productName:
          type: string
          example: Sticker Custom A3
        sku:
          type: string
          example: STK-A3-001
        thumbnail:
          type: string
          format: uri
        currentStock:
          type: integer
          example: 50
        reservedStock:
          type: integer
          example: 5
        availableStock:
          type: integer
          example: 45
        lowStockThreshold:
          type: integer
          example: 10
        status:
          type: string
          enum: [in_stock, low_stock, out_of_stock]
          example: in_stock
        lastRestocked:
          type: string
          format: date-time
          nullable: true
        updatedAt:
          type: string
          format: date-time

    InventoryDetail:
      allOf:
        - $ref: '#/components/schemas/InventoryItem'
        - type: object
          properties:
            variations:
              type: array
              items:
                type: object
                properties:
                  variationId:
                    $ref: '../components/schemas/common.yaml#/UUID'
                  name:
                    type: string
                  currentStock:
                    type: integer
                  reservedStock:
                    type: integer
                  availableStock:
                    type: integer
            recentMovements:
              type: array
              items:
                $ref: '#/components/schemas/StockMovement'

    InventoryUpdateRequest:
      type: object
      properties:
        currentStock:
          type: integer
          minimum: 0
        lowStockThreshold:
          type: integer
          minimum: 0
        notes:
          type: string
          nullable: true

    StockMovement:
      type: object
      properties:
        id:
          $ref: '../components/schemas/common.yaml#/UUID'
        product:
          type: object
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
            sku:
              type: string
        variation:
          type: object
          nullable: true
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
        type:
          type: string
          enum: [in, out, adjustment]
          example: in
        quantity:
          type: integer
          example: 100
        previousStock:
          type: integer
          example: 50
        newStock:
          type: integer
          example: 150
        reason:
          type: string
          example: Restock from supplier
        reference:
          type: string
          nullable: true
          description: Reference number (e.g., PO number, order number)
        performedBy:
          type: object
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
        createdAt:
          type: string
          format: date-time

    StockMovementRequest:
      type: object
      required:
        - productId
        - type
        - quantity
      properties:
        productId:
          type: string
          format: uuid
        variationId:
          type: string
          format: uuid
          nullable: true
        type:
          type: string
          enum: [in, out, adjustment]
        quantity:
          type: integer
          minimum: 1
        reason:
          type: string
          minLength: 3
        reference:
          type: string
          nullable: true

    StockAlert:
      type: object
      properties:
        productId:
          $ref: '../components/schemas/common.yaml#/UUID'
        productName:
          type: string
        sku:
          type: string
        currentStock:
          type: integer
        threshold:
          type: integer
        alertType:
          type: string
          enum: [low_stock, out_of_stock]

    InventorySummary:
      type: object
      properties:
        totalProducts:
          type: integer
          example: 250
        totalValue:
          type: number
          format: float
          example: 125000000
        lowStockProducts:
          type: integer
          example: 15
        outOfStockProducts:
          type: integer
          example: 5
