openapi: 3.0.3
info:
  title: Language & Localization Module API
  version: 1.0.0

paths:
  /api/v1/languages:
    get:
      tags:
        - Language
      summary: Get available languages (Public)
      description: Retrieve list of available languages
      responses:
        '200':
          description: Languages retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Language'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/translations/{locale}:
    get:
      tags:
        - Language
      summary: Get translations for locale (Public)
      description: Retrieve all translations for specific language
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
            example: en
        - name: namespace
          in: query
          schema:
            type: string
          description: Filter by namespace (e.g., common, auth, products)
      responses:
        '200':
          description: Translations retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      "common.welcome": "Welcome"
                      "common.logout": "Logout"
                      "products.title": "Products"
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/languages:
    get:
      tags:
        - Language
      summary: Get all languages (Admin)
      description: Retrieve all languages with management info
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Languages retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LanguageAdmin'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Language
      summary: Add new language (Admin)
      description: Add a new language to the system
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LanguageRequest'
      responses:
        '201':
          description: Language added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/LanguageAdmin'
                  message:
                    type: string
                    example: Language added successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/languages/{locale}:
    put:
      tags:
        - Language
      summary: Update language (Admin)
      description: Update language settings
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LanguageRequest'
      responses:
        '200':
          description: Language updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/LanguageAdmin'
                  message:
                    type: string
                    example: Language updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    delete:
      tags:
        - Language
      summary: Delete language (Admin)
      description: Remove a language from the system
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Language deleted successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/SuccessResponse'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          description: Cannot delete default language
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/ErrorResponse'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/translations:
    get:
      tags:
        - Translations
      summary: Get all translations (Admin)
      description: Retrieve all translation keys and values
      security:
        - bearerAuth: []
      parameters:
        - name: locale
          in: query
          schema:
            type: string
          description: Filter by locale
        - name: namespace
          in: query
          schema:
            type: string
          description: Filter by namespace
        - $ref: '../components/parameters/common.yaml#/SearchQuery'
      responses:
        '200':
          description: Translations retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Translation'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Translations
      summary: Create translation (Admin)
      description: Add a new translation key
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslationRequest'
      responses:
        '201':
          description: Translation created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Translation'
                  message:
                    type: string
                    example: Translation created successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/translations/{id}:
    put:
      tags:
        - Translations
      summary: Update translation (Admin)
      description: Update translation value
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - value
              properties:
                value:
                  type: string
      responses:
        '200':
          description: Translation updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Translation'
                  message:
                    type: string
                    example: Translation updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    delete:
      tags:
        - Translations
      summary: Delete translation (Admin)
      description: Remove a translation key
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Translation deleted successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/SuccessResponse'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/translations/import:
    post:
      tags:
        - Translations
      summary: Import translations (Admin)
      description: Bulk import translations from JSON file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - locale
              properties:
                file:
                  type: string
                  format: binary
                locale:
                  type: string
                overwrite:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Translations imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      imported:
                        type: integer
                        example: 150
                      skipped:
                        type: integer
                        example: 5
                  message:
                    type: string
                    example: Translations imported successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/admin/translations/export:
    post:
      tags:
        - Translations
      summary: Export translations (Admin)
      description: Export translations as JSON file
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - locale
              properties:
                locale:
                  type: string
                namespace:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Translations exported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      downloadUrl:
                        type: string
                        format: uri
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

components:
  schemas:
    Language:
      type: object
      properties:
        locale:
          type: string
          example: en
        name:
          type: string
          example: English
        nativeName:
          type: string
          example: English
        isDefault:
          type: boolean
          example: false
        isActive:
          type: boolean
          example: true

    LanguageAdmin:
      allOf:
        - $ref: '#/components/schemas/Language'
        - type: object
          properties:
            direction:
              type: string
              enum: [ltr, rtl]
              example: ltr
            translationProgress:
              type: number
              format: float
              example: 95.5
              description: Percentage of translated keys
            totalKeys:
              type: integer
              example: 500
            translatedKeys:
              type: integer
              example: 477
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    LanguageRequest:
      type: object
      required:
        - locale
        - name
        - nativeName
      properties:
        locale:
          type: string
          pattern: "^[a-z]{2}$"
          example: id
        name:
          type: string
          example: Indonesian
        nativeName:
          type: string
          example: Bahasa Indonesia
        direction:
          type: string
          enum: [ltr, rtl]
          default: ltr
        isActive:
          type: boolean
          default: true
        isDefault:
          type: boolean
          default: false

    Translation:
      type: object
      properties:
        id:
          $ref: '../components/schemas/common.yaml#/UUID'
        key:
          type: string
          example: common.welcome
        namespace:
          type: string
          example: common
        locale:
          type: string
          example: en
        value:
          type: string
          example: Welcome
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    TranslationRequest:
      type: object
      required:
        - key
        - locale
        - value
      properties:
        key:
          type: string
          pattern: "^[a-z0-9._-]+$"
          example: products.add_to_cart
        namespace:
          type: string
          example: products
        locale:
          type: string
        value:
          type: string
          minLength: 1
