openapi: 3.0.3
info:
  title: Media Library Module API
  version: 1.0.0

paths:
  /api/v1/media:
    get:
      tags:
        - Media Library
      summary: Get all media files (Admin)
      description: Retrieve paginated list of all media files
      security:
        - bearerAuth: []
      parameters:
        - $ref: '../components/parameters/common.yaml#/PageQuery'
        - $ref: '../components/parameters/common.yaml#/PerPageQuery'
        - $ref: '../components/parameters/common.yaml#/SearchQuery'
        - $ref: '../components/parameters/common.yaml#/SortQuery'
        - name: type
          in: query
          schema:
            type: string
            enum: [image, video, document, audio, other]
          description: Filter by file type
        - name: folderId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by folder ID (null for root)
      responses:
        '200':
          description: Media files retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MediaFile'
                  meta:
                    allOf:
                      - $ref: '../components/schemas/common.yaml#/PaginationMeta'
                      - type: object
                        properties:
                          storageUsed:
                            type: integer
                            description: Total storage used in bytes
                            example: 1073741824
                          storageLimit:
                            type: integer
                            description: Storage limit in bytes
                            example: 5368709120
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Media Library
      summary: Upload media file (Admin)
      description: Upload a new file to media library
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                folderId:
                  type: string
                  format: uuid
                title:
                  type: string
                alt:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/MediaFile'
                  message:
                    type: string
                    example: File uploaded successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/ErrorResponse'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/media/{id}:
    get:
      tags:
        - Media Library
      summary: Get media file by ID (Admin)
      description: Retrieve detailed information about a media file
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Media file retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/MediaFileDetail'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    put:
      tags:
        - Media Library
      summary: Update media file metadata (Admin)
      description: Update file title, alt text, and other metadata
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaUpdateRequest'
      responses:
        '200':
          description: Media file updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/MediaFile'
                  message:
                    type: string
                    example: Media file updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    delete:
      tags:
        - Media Library
      summary: Delete media file (Admin)
      description: Permanently delete a media file
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Media file deleted successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/SuccessResponse'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          description: File is in use and cannot be deleted
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/ErrorResponse'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/media/folders:
    get:
      tags:
        - Media Folders
      summary: Get all folders (Admin)
      description: Retrieve hierarchical list of media folders
      security:
        - bearerAuth: []
      parameters:
        - name: parent
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by parent folder ID (null for root)
      responses:
        '200':
          description: Folders retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MediaFolder'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    post:
      tags:
        - Media Folders
      summary: Create new folder (Admin)
      description: Create a new media folder
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderRequest'
      responses:
        '201':
          description: Folder created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/MediaFolder'
                  message:
                    type: string
                    example: Folder created successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

  /api/v1/media/folders/{id}:
    put:
      tags:
        - Media Folders
      summary: Update folder (Admin)
      description: Update folder name or parent
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FolderRequest'
      responses:
        '200':
          description: Folder updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/MediaFolder'
                  message:
                    type: string
                    example: Folder updated successfully
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          $ref: '../components/responses/common.yaml#/ValidationError'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

    delete:
      tags:
        - Media Folders
      summary: Delete folder (Admin)
      description: Delete a media folder (must be empty)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Folder deleted successfully
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/SuccessResponse'
        '401':
          $ref: '../components/responses/common.yaml#/Unauthorized'
        '403':
          $ref: '../components/responses/common.yaml#/Forbidden'
        '404':
          $ref: '../components/responses/common.yaml#/NotFound'
        '422':
          description: Folder is not empty
          content:
            application/json:
              schema:
                $ref: '../components/schemas/common.yaml#/ErrorResponse'
        '500':
          $ref: '../components/responses/common.yaml#/ServerError'

components:
  schemas:
    MediaFile:
      type: object
      properties:
        id:
          $ref: '../components/schemas/common.yaml#/UUID'
        filename:
          type: string
          example: product-image-01.jpg
        originalName:
          type: string
          example: my-product.jpg
        title:
          type: string
          nullable: true
          example: Product Image
        alt:
          type: string
          nullable: true
          example: High quality product image
        description:
          type: string
          nullable: true
        url:
          type: string
          format: uri
          example: https://cdn.example.com/media/product-image-01.jpg
        thumbnailUrl:
          type: string
          format: uri
          nullable: true
        type:
          type: string
          enum: [image, video, document, audio, other]
          example: image
        mimeType:
          type: string
          example: image/jpeg
        size:
          type: integer
          description: File size in bytes
          example: 1048576
        dimensions:
          type: object
          nullable: true
          properties:
            width:
              type: integer
              example: 1920
            height:
              type: integer
              example: 1080
        folder:
          type: object
          nullable: true
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
        uploadedBy:
          type: object
          properties:
            id:
              $ref: '../components/schemas/common.yaml#/UUID'
            name:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    MediaFileDetail:
      allOf:
        - $ref: '#/components/schemas/MediaFile'
        - type: object
          properties:
            usageCount:
              type: integer
              description: Number of times this file is used
              example: 5
            usedIn:
              type: array
              description: List of entities using this file
              items:
                type: object
                properties:
                  type:
                    type: string
                    example: product
                  id:
                    $ref: '../components/schemas/common.yaml#/UUID'
                  title:
                    type: string

    MediaUpdateRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
        alt:
          type: string
          maxLength: 255
        description:
          type: string
          maxLength: 1000
        folderId:
          type: string
          format: uuid
          nullable: true

    MediaFolder:
      type: object
      properties:
        id:
          $ref: '../components/schemas/common.yaml#/UUID'
        name:
          type: string
          example: Product Images
        parentId:
          type: string
          format: uuid
          nullable: true
        filesCount:
          type: integer
          example: 24
        subfolders:
          type: array
          items:
            $ref: '#/components/schemas/MediaFolder'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    FolderRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        parentId:
          type: string
          format: uuid
          nullable: true
