# Base Entity Schemas for Stencil CMS
# Common schemas used across all modules

# Base Entity with Multi-tenant Support
BaseEntity:
  type: object
  required:
    - id
    - tenant_id
    - created_at
    - updated_at
  properties:
    id:
      type: string
      format: uuid
      description: Unique identifier (UUID v4)
      example: "550e8400-e29b-41d4-a716-446655440000"
      readOnly: true
    tenant_id:
      type: string
      format: uuid
      description: Tenant isolation identifier - MANDATORY for all entities
      example: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
      readOnly: true
    created_at:
      type: string
      format: date-time
      description: Creation timestamp (ISO 8601)
      example: "2025-11-12T13:00:00Z"
      readOnly: true
    updated_at:
      type: string
      format: date-time
      description: Last modification timestamp (ISO 8601)
      example: "2025-11-12T13:30:00Z"
      readOnly: true
    deleted_at:
      type: string
      format: date-time
      nullable: true
      description: Soft deletion timestamp (ISO 8601)
      example: null
      readOnly: true

# Base Entity for Creation Requests (without system-generated fields)
BaseCreateEntity:
  type: object
  properties:
    # No id, tenant_id, timestamps - these are system-generated
    tenant_id:
      type: string
      format: uuid
      description: Tenant isolation identifier (set by authentication middleware)
      example: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
      readOnly: true

# Base Entity for Update Requests (only updatable fields)
BaseUpdateEntity:
  type: object
  properties:
    updated_at:
      type: string
      format: date-time
      description: Last modification timestamp (system-generated)
      example: "2025-11-12T13:30:00Z"
      readOnly: true

# Soft Delete Entity
SoftDeletableEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        deleted_at:
          type: string
          format: date-time
          nullable: true
          description: Soft deletion timestamp (null if not deleted)
          example: null

# Audit Entity (with created_by, updated_by tracking)
AuditableEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        created_by:
          type: string
          format: uuid
          nullable: true
          description: ID of user who created this entity
          example: "550e8400-e29b-41d4-a716-446655440000"
        updated_by:
          type: string
          format: uuid
          nullable: true
          description: ID of user who last updated this entity
          example: "550e8400-e29b-41d4-a716-446655440000"

# Enhanced Audit Entity (for critical operations)
AuditEntity:
  allOf:
    - $ref: '#/AuditableEntity'
    - type: object
      properties:
        audit_log:
          type: array
          description: Detailed audit trail
          items:
            type: object
            properties:
              action:
                type: string
                description: Action performed
                example: "updated"
              field:
                type: string
                description: Field that was changed
                example: "status"
              old_value:
                type: string
                nullable: true
                description: Previous value
                example: "draft"
              new_value:
                type: string
                nullable: true
                description: New value
                example: "published"
              timestamp:
                type: string
                format: date-time
                description: When the change occurred
                example: "2025-11-12T13:30:00Z"
              user_id:
                type: string
                format: uuid
                nullable: true
                description: User who made the change
                example: "550e8400-e29b-41d4-a716-446655440000"

# Visibility Entity (for content with visibility controls)
VisibilityEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        is_visible:
          type: boolean
          description: Whether the entity is visible
          example: true
          default: true
        visibility_rules:
          type: object
          description: Complex visibility rules (JSON)
          nullable: true
          properties:
            show_to:
              type: array
              description: User roles that can see this
              items:
                type: string
              example: ["admin", "editor", "user"]
            hide_from:
              type: array
              description: User roles that cannot see this
              items:
                type: string
              example: ["guest"]
            start_date:
              type: string
              format: date-time
              nullable: true
              description: When to start showing
              example: "2025-11-12T00:00:00Z"
            end_date:
              type: string
              format: date-time
              nullable: true
              description: When to stop showing
              example: "2025-12-12T23:59:59Z"

# Orderable Entity (for drag-drop sorting)
OrderableEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        sort_order:
          type: integer
          description: Display order (lower numbers appear first)
          example: 1
          minimum: 0

# Status Entity (for entities with active/inactive states)
StatusEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        status:
          type: string
          enum: [active, inactive, draft, archived]
          description: Current status of the entity
          example: "active"
          default: "active"

# SEO-enabled Entity (for content with SEO metadata)
SEOEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        seo_meta:
          type: object
          description: SEO metadata (polymorphic relationship)
          nullable: true
          properties:
            title:
              type: string
              description: SEO title (overrides default)
              example: "Custom SEO Title"
              maxLength: 60
            description:
              type: string
              description: SEO meta description
              example: "Custom meta description for search engines"
              maxLength: 160
            keywords:
              type: array
              description: SEO keywords
              items:
                type: string
              example: ["etching", "custom", "manufacturing"]
            og_image:
              type: string
              format: uri
              description: Open Graph image URL
              example: "https://example.com/og-image.jpg"
            canonical_url:
              type: string
              format: uri
              description: Canonical URL for this content
              example: "https://example.com/canonical-url"

# Translatable Entity (for multi-language content)
TranslatableEntity:
  allOf:
    - $ref: '#/BaseEntity'
    - type: object
      properties:
        locale:
          type: string
          description: Content locale (ISO 639-1)
          example: "en"
          pattern: "^[a-z]{2}$"
        translations:
          type: object
          description: Translation data for different locales
          additionalProperties:
            type: object
            description: Translated content for specific locale
          example:
            en:
              title: "English Title"
              content: "English content"
            id:
              title: "Judul Bahasa Indonesia"
              content: "Konten bahasa Indonesia"

# Publishable Entity (for content with publish/unpublish states)
PublishableEntity:
  allOf:
    - $ref: '#/StatusEntity'
    - type: object
      properties:
        published_at:
          type: string
          format: date-time
          nullable: true
          description: Publication timestamp
          example: "2025-11-12T13:00:00Z"
        unpublished_at:
          type: string
          format: date-time
          nullable: true
          description: Unpublication timestamp
          example: null
        is_published:
          type: boolean
          description: Current publication status
          example: true
          readOnly: true

# Versioned Entity (for content with version history)
VersionedEntity:
  allOf:
    - $ref: '#/AuditableEntity'
    - type: object
      properties:
        version:
          type: integer
          description: Current version number
          example: 1
          minimum: 1
          readOnly: true
        version_notes:
          type: string
          description: Notes about this version
          example: "Updated content and layout"
          maxLength: 500

# Common JSON Schema Properties
JSONContent:
  type: object
  description: Flexible JSON content storage
  additionalProperties: true
  example:
    custom_field_1: "value1"
    custom_field_2: 123
    nested_object:
      property: "value"

# Common File Upload Schema
FileUpload:
  type: object
  required:
    - filename
    - mime_type
    - size
  properties:
    filename:
      type: string
      description: Original filename
      example: "document.pdf"
    mime_type:
      type: string
      description: File MIME type
      example: "application/pdf"
    size:
      type: integer
      description: File size in bytes
      example: 1048576
    url:
      type: string
      format: uri
      description: File access URL
      example: "https://cdn.example.com/files/document.pdf"
    thumbnail_url:
      type: string
      format: uri
      nullable: true
      description: Thumbnail URL (for images/videos)
      example: "https://cdn.example.com/thumbs/document_thumb.jpg"

# Color Schema (for theming)
ColorValue:
  type: string
  pattern: "^#[0-9A-Fa-f]{6}$"
  description: Hexadecimal color value
  example: "#FF5733"

# URL Schema with Validation
URLValue:
  type: string
  format: uri
  description: Valid URL
  example: "https://example.com/path"

# Email Schema with Validation
EmailValue:
  type: string
  format: email
  description: Valid email address
  example: "user@example.com"

# Phone Number Schema
PhoneValue:
  type: string
  pattern: "^\\+?[1-9]\\d{1,14}$"
  description: Valid phone number (international format)
  example: "+62812345678"

# Slug Schema (URL-safe identifier)
SlugValue:
  type: string
  pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
  description: URL-safe slug (lowercase, hyphens only)
  example: "this-is-a-slug"

# Rich Text Content Schema
RichTextContent:
  type: object
  properties:
    raw:
      type: string
      description: Raw content (HTML or Markdown)
      example: "<h1>Title</h1><p>Content with <strong>formatting</strong></p>"
    plain:
      type: string
      description: Plain text version (for search indexing)
      example: "Title Content with formatting"
      readOnly: true
    word_count:
      type: integer
      description: Word count (auto-calculated)
      example: 4
      readOnly: true

# Common Validation Errors Schema
ValidationError:
  type: object
  properties:
    field:
      type: string
      description: Field name with validation error
      example: "email"
    message:
      type: string
      description: Human-readable error message
      example: "The email field is required"
    code:
      type: string
      description: Machine-readable error code
      example: "required"