<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class OrderDocumentResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'document_number' => $this->document_number,
            'document_type' => $this->document_type,
            'version' => $this->version,
            
            // File information (both nested and flat for compatibility)
            'file_path' => $this->file_path,
            'file_url' => $this->file_url,
            'file_size' => $this->file_size,
            'file' => [
                'path' => $this->file_path,
                'url' => $this->file_url,
                'size' => $this->file_size,
                'size_formatted' => $this->formatFileSize($this->file_size),
            ],
            
            // Status
            'status' => $this->status,
            
            // Relationships
            'customer_quote_id' => $this->customer_quote_id,
            'template_id' => $this->template_id,
            
            // Generated by
            'generated_by' => $this->whenLoaded('generatedBy', function () {
                return [
                    'id' => $this->generatedBy->id,
                    'name' => $this->generatedBy->name,
                    'email' => $this->generatedBy->email,
                ];
            }),
            
            // Metadata
            'metadata' => $this->metadata,
            
            // Timestamps
            'generated_at' => $this->generated_at?->toIso8601String(),
            'created_at' => $this->created_at?->toIso8601String(),
            'updated_at' => $this->updated_at?->toIso8601String(),
        ];
    }

    /**
     * Format file size to human readable format
     */
    private function formatFileSize(?int $bytes): ?string
    {
        if ($bytes === null) {
            return null;
        }

        $units = ['B', 'KB', 'MB', 'GB'];
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        $bytes /= (1 << (10 * $pow));

        return round($bytes, 2) . ' ' . $units[$pow];
    }
}
